- include_tasks: prerequesites.yaml

- include_tasks: control_plane.yaml
  when: inventory_hostname in groups['control_plane']

- include_tasks: workers.yaml
  when: inventory_hostname not in groups['control_plane']