- name: Check if node already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: node_check

- name: Get join command from control plane
  shell: kubeadm token create --print-join-command
  delegate_to: "{{ groups['control_plane'][0] }}"
  register: join_cmd
  become: true
  when: not node_check.stat.exists

- name: Join cluster
  command: "{{ join_cmd.stdout }}"
  become: true
  when: not node_check.stat.exists